"""baseline schema

Revision ID: 17500b0244be
Revises: 
Create Date: 2026-07-20 19:25:05.123467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17500b0244be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('capital_gains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('term', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_section', sa.String(length=10), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('capital_gains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_capital_gains_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_capital_gains_user_id'), ['user_id'], unique=False)

    op.create_table('deductions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('claimed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deductions_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_deductions_user_id'), ['user_id'], unique=False)

    op.create_table('income_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('exemptions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tds_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_sources_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_sources_user_id'), ['user_id'], unique=False)

    op.create_table('insurances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('premium', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('for_senior_citizen', sa.Boolean(), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_insurances_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_insurances_user_id'), ['user_id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('invested_on', sa.Date(), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_user_id'), ['user_id'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('principal_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('pan_encrypted', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('residential_status', sa.String(length=30), nullable=False),
    sa.Column('preferred_regime', sa.String(length=10), nullable=True),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tax_computations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('regime', sa.String(length=10), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('refund_or_due', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rules_version', sa.String(length=30), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_computations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_computations_assessment_year'), ['assessment_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_computations_user_id'), ['user_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('computation_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('estimated_saving', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount_modelled', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('required_documents', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['computation_id'], ['tax_computations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_computation_id'), ['computation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendations_computation_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('tax_computations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_computations_user_id'))
        batch_op.drop_index(batch_op.f('ix_tax_computations_assessment_year'))

    op.drop_table('tax_computations')
    op.drop_table('profiles')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))
        batch_op.drop_index(batch_op.f('ix_loans_assessment_year'))

    op.drop_table('loans')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_user_id'))
        batch_op.drop_index(batch_op.f('ix_investments_assessment_year'))

    op.drop_table('investments')
    with op.batch_alter_table('insurances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_insurances_user_id'))
        batch_op.drop_index(batch_op.f('ix_insurances_assessment_year'))

    op.drop_table('insurances')
    with op.batch_alter_table('income_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_sources_assessment_year'))

    op.drop_table('income_sources')
    with op.batch_alter_table('deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deductions_user_id'))
        batch_op.drop_index(batch_op.f('ix_deductions_assessment_year'))

    op.drop_table('deductions')
    with op.batch_alter_table('capital_gains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_capital_gains_user_id'))
        batch_op.drop_index(batch_op.f('ix_capital_gains_assessment_year'))

    op.drop_table('capital_gains')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
